// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace AnyDocToMarkdown.Native
{
    internal static unsafe partial class AnydocNative
    {
        const string __DllName = "anydoc_dotnet";





        /// <summary>
        ///  `format_from_bytes`: detect the format from the content.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "anydoc_format_from_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int anydoc_format_from_bytes(byte* bytes, nuint len);

        /// <summary>
        ///  `format_from_extension`: the format a (possibly dot-prefixed) extension names.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "anydoc_format_from_extension", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int anydoc_format_from_extension(byte* bytes, nuint len);

        /// <summary>
        ///  `format_from_path`: the format a path's extension names.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "anydoc_format_from_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int anydoc_format_from_path(byte* bytes, nuint len);

        /// <summary>
        ///  `to_markdown(path)`: convert a file, detecting the format from its content.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "anydoc_to_markdown_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void anydoc_to_markdown_path(byte* path, nuint len, AnyResult* result);

        /// <summary>
        ///  `to_markdown_bytes`: convert in-memory bytes; `format` of `-1` detects it.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "anydoc_to_markdown_bytes", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void anydoc_to_markdown_bytes(byte* bytes, nuint len, int format, AnyResult* result);

        /// <summary>
        ///  `to_document`: parse in-memory byte array into the document model, returned as
        ///  JSON. Unsupported for PDF, like the other bindings.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "anydoc_to_document", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void anydoc_to_document(byte* bytes, nuint len, int format, AnyResult* result);

        /// <summary>
        ///  Release everything `*result` holds: the error strings and the data buffer.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "anydoc_free_result", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void anydoc_free_result(AnyResult* result);


    }

    /// <summary>
    ///  An owned byte buffer; `ptr` is null and `len` zero when empty.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public nuint len;
        public nuint capacity;
    }

    /// <summary>
    ///  The outcome of a conversion. `ok` selects between the payload and the error
    ///  fields; the caller hands the whole struct back to [`anydoc_free_result`].
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct AnyResult
    {
        [MarshalAs(UnmanagedType.U1)] public bool ok;
        /// <summary>
        ///  Machine-readable kind (`error.code()`), null when `ok`.
        /// </summary>
        public byte* error_code;
        /// <summary>
        ///  Human-readable message, null when `ok`.
        /// </summary>
        public byte* error_message;
        /// <summary>
        ///  Markdown, or the document model as JSON, when `ok`.
        /// </summary>
        public ByteBuffer data;
    }



}
